# Generated by Django 4.2.4 on 2023-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_featuredimage_startupimage_storyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='image_gallery')),
                ('description', models.TextField(blank=True, default='N/A', null=True)),
                ('show', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeaturedImage',
        ),
    ]
